[package]
name = "bluetooth-command"
version = "0.1.0"
edition = "2021"

[dependencies]
bluest = "0.6.7"
futures-lite = "2.6.0"
tokio = { version = "1.44.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
